In [1]:
        # self.num_features = [int(embed_dim * 2**i) for i in range(self.num_levels)]
num_feat = [int(32 * 2**i) for i in range(3)]
print(num_feat)

[32, 64, 128]


In [2]:
import torch
a=torch.linspace(0,0.2,4)
print(a)

/home/amax/HHD/24-Zhong.zt/Miniconda3/envs/vtp/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([0.0000, 0.0667, 0.1333, 0.2000])


In [ ]:
import torch
mask = torch.ones(3,3).bool()
print(mask)
invaild_mask = ~mask.all(-1)
print(invaild_mask)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])
